language: ruby
rvm:
- 2.1
script: bundle exec rake
bundler_args: "--binstubs"
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: qGST5poXc3IpSQgLKhTaRujHYWVl2qWM4BuwG4Uf80XZhj8ZStq2lwAyWrv/WADbkpFUDxLDUBXVSAaOAHXoyUlGTbtTJEWPrRsAb065B4KboRyqV/v6ZtfUaadROiZGfUpVNC4PXtI+SAY6JjoJoBJ3F0WG49yFTdQ3MmwMpe962TTHKNZEnhZLUvpwcUVxJVo0/7Gt94oDMGkQ1RmAiENejvVJexW17/HCW/PkNWt0cy5aPzQxVFwSZ7UNKCTuK6/zrScIHoVdnvUnlQ3SWUozHcMkJTAjIN/SHI6O8BW+1qDjEnknr7siqPEMtlT7F0KnT4On9kJYvXdyxn3mQk+mtT5F9ZfIcDse8qno6/GIcFBmuN2QIAChedCG3JP4TD3lgn+tQ/kIespivJp4Fi2iugQX4tkl77jtapufmaGEdjszXGcV6kIgld3O12wkhXc3r0o/NBmeHR2sG3xyoiA5He9Rp6jTgu5Oor3LTufwqpySqV9XLTrdTWZxMQQ04reUquwnS32VJBWZYhKpQtchg8U8kfSK9M06zZberqV/PQIZjbzXO0wSKymyXWJbIo4dX25osLk27GGK4+tkfZ0AcmAb6R0B3hxiBFItdprkGskfKBJE21HjeD7Taz9T2yxoFZAZ364lemRrP37UDTe3t9S3SSkJfedacaOW3OY=
install:
- git config --global user.email "davidnaffis@gmail.com"
- git config --global user.name "naffis"
- bundle install
